print("Fork this repository")
print("Then clone the repository locally")
print("change the hello.py file")
print("also create a new file")
print("Commit both of these")
print("Make separate pull requests")
